framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
            - de
        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['messages']
                locales: ['en', 'de']
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
