version: '3.7'

services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: therapy_scheme_generator
            MYSQL_USER: app_user
            MYSQL_PASSWORD: app_password
        ports:
            - '3306:3306'
        volumes:
            - ./.docker/mysql:/var/lib/mysql
            
    php:
        container_name: php
        build:
            context: ./.docker/php
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/application
        depends_on:
            - database
    
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www/application
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database